### ISSUE TITLE
Control frozen pre network initialization

### ISSUE THREAD

**Issue by natolambert** [PisterLab/BotNet#1]
(low effect on almost all experiments)

The first few cycles of control laws are not applied while the network creates its neighbors. Maybe we change this to random walk until the network converges?

How to do this better is an open research question.

Such as from @callmecampos:
> plit up the slotframe such that some proportion is dedicated towards location broadcasting and another portion is dedicated towards negotiating network dynamics etc. (I’m likely not actually going to do this, but it’s an example that even Kris has given about being more intelligent about schedule function design to acommodate other types of data being sent alongside location

**Comment by callmecampos** [comment]
Fixed in [this commit](1c96f5a64c6e098cd78efd3bcfef0f20960ca674) and [this commit](880dac86a9f102fb7ada315f91cc428cb7d90465), however this still doesn't solve the issue of enhanced beacons occasionally being sent even after initialization in case other motes want to join the network.

Not a huge deal, but worth thinking about future scheduling function design.
